Master 6
111Mihail111/EVENTIME pull request #7
Opened 2022-02-25 13:38 UTC by kitovras

2022-02-25 13:40 UTC, 111Mihail111 requested changes
д

2022-02-25 13:41 UTC, 111Mihail111 approved these changes
з

2022-02-25 13:43 UTC, 111Mihail111 requested changes

2022-02-25 13:43 UTC, 111Mihail111 commented on bootstrap/css/custom-styles.css
> +.image-test {
Плохое название

2022-02-25 13:53 UTC, JEN1011 approved these changes

2022-02-25 14:01 UTC, DjWaRCovAiK approved these changes

2022-02-25 17:27 UTC, 111Mihail111 requested changes
Написал замечания

2022-02-25 17:27 UTC, 111Mihail111 commented on pages/index.html
> +                                    <span class="text-dark pt-1 pb-1 ps-3 pe-3 mt-2" style="border-radius: 30px; background-color: white; font-size: 12px; display: inline-block">Бесплатно</span>
Удали класс text-dark здесь и ниже. С ним или без - выглядит одинаково

2022-02-25 17:27 UTC, 111Mihail111 commented on pages/index.html
> +        <div class="row mt-3">
Добавь еще 2 карточки по горизонтали в этой строке. И ниже потом еще одну строку с 3-мя карточками

2022-03-01 07:14 UTC, 111Mihail111 approved these changes

2022-03-01 16:01 UTC, merged