Master 8
111Mihail111/EVENTIME pull request #8
Opened 2022-02-26 17:40 UTC by DjWaRCovAiK

2022-03-01 17:08 UTC, JEN1011 approved these changes

2022-03-01 17:43 UTC, 111Mihail111 requested changes

2022-03-01 17:43 UTC, 111Mihail111 commented on pages/manualDataEntry.html
> +                    <input class="form-control no-focus-outline" style="display: inline-block;" type="text" placeholder="Наименование" />
Давай еще заголовок выведем на строкой фильтра, чтобы понятней было, по чем фильтрует то или иной поле.
Сюда добавь label с текстом "Наименование организации:" и сделай жирным

2022-03-01 17:43 UTC, 111Mihail111 commented on pages/manualDataEntry.html
> +                    <input class="form-control no-focus-outline" style="display: inline-block;" type="text" placeholder="Адрес" />
А здесь label с "Адрес организации:" и тоже жирным

2022-03-01 17:43 UTC, 111Mihail111 commented on pages/manualDataEntry.html
> +                    <input class="form-control no-focus-outline" style="display: inline-block;" type="text" placeholder="Название" />
А здесь label с "Название мероприятия:" и тоже жирным

2022-03-01 17:43 UTC, 111Mihail111 commented on pages/manualDataEntry.html
> +                    <input class="form-control no-focus-outline" style="display: inline-block;" type="text" placeholder="Дата и время" />
1) А здесь label с "Время проведения:" и тоже жирным
2) В этом инпуте я должен выбирать дату и время, а не текст писать. Поменяй его type

2022-03-01 17:43 UTC, 111Mihail111 commented on pages/manualDataEntry.html
> +                    <select class="form-select text-center no-focus-outline">
А здесь label с "Категория:" и тоже жирным

2022-03-01 17:43 UTC, 111Mihail111 commented on pages/manualDataEntry.html
> +                        <option></option>
Тоже пока добавь "Все"

2022-03-01 17:43 UTC, 111Mihail111 commented on pages/manualDataEntry.html
> +                <div class="row justify-content-end">
Не особо понимаю, какую функциональную роль выполняет этот div. Посмотри по коду, возможно лишнее, а если нет, отпишись сюда, для чего он нужен

2022-03-01 17:43 UTC, 111Mihail111 commented on pages/manualDataEntry.html
> +                                        <img src="../images/ImageNotFound.jpg" style="border-radius: 50px; width: 100%; height: 100%;" />
Картинка не та, ну да ладно, это макет, так что не критично, пусть будет

2022-03-01 17:43 UTC, 111Mihail111 commented on pages/manualDataEntry.html
> +    <div class="modal fade" id="addOrganizationWindow" tabindex="-1" data-bs-backdrop="static" aria-hidder="true">
У модального окна должны быть закругленные углы

2022-03-01 17:43 UTC, 111Mihail111 commented on pages/manualDataEntry.html
> +                                    <div class="col-2">
Я вроде говорил удалить все чекбоксы из модалок, еще давно, так как на этой странице не будет того функционала, на который они рассчитаны.

2022-03-01 17:43 UTC, 111Mihail111 commented on pages/manualDataEntry.html
> +                                        <input class="form-control no-focus-outline" style="display: inline-block;" type="text" />
Все инпуты в модальных окнах должны иметь закругленные края с обоих сторон

2022-03-01 17:43 UTC, 111Mihail111 commented on pages/manualDataEntry.html
> +                                        <select class="form-select text-center no-focus-outline"></select>
Категории заведения должны быть заполнены. "Все" - первый option по умолчанию

2022-03-01 17:43 UTC, 111Mihail111 commented on pages/manualDataEntry.html
> +                                        <buttom class="btn" style="background-color: #d9d9d9; border-radius: 15px;">Зарегистрироваться</buttom>
Текст в кнопке - в спан. Тексту внутри дать отступы слева и права. см скрин в задаче по этому окну.

2022-03-01 17:43 UTC, 111Mihail111 commented on pages/manualDataEntry.html
> +                <div class="row justify-content-end">
Не особо понимаю, какую функциональную роль выполняет этот div. Посмотри по коду, возможно лишнее, а если нет, отпишись сюда, для чего он нужен

2022-03-01 17:43 UTC, 111Mihail111 commented on pages/manualDataEntry.html
> +                                    <div class="col-2">
Тоже вычисти все чекбоксы

2022-03-01 17:43 UTC, 111Mihail111 commented on pages/manualDataEntry.html
> +                                            <span class="fs-cust-3">5+</span>
У возрастных ограничений должна быть обводка

2022-03-01 17:43 UTC, 111Mihail111 commented on pages/manualDataEntry.html
> +                                        <button class="btn no-focus-outline fw-1">Опубликовать</button>
Добавить обводку и отступы. см. скрин в задаче по этому окну

2022-03-01 17:43 UTC, 111Mihail111 commented on pages/manualDataEntry.html
> +                                    <button class="fw-1 btn no-focus-outline btn-outline-success">Редактировать</button><br>
Выше кнопка синяя, а здесь зеленая - приведи к общему стилю. Либо зеленая, либо синяя.

2022-03-01 17:43 UTC, 111Mihail111 commented on pages/manualDataEntry.html
> +                                <th scope="row">1</th>
Почему здесь scope="row", а везде ниже scope="col". Есть какая-та принципиальная разница? Если да, отпишись здесь, если нет - исправь здесь и везде ниже по таблице

2022-03-01 17:43 UTC, 111Mihail111 commented on pages/manualDataEntry.html
> +                        <div class="col-8">
Лишнее. Этот кол удали, а кнопки засунь в div col-12

2022-03-02 18:08 UTC, 111Mihail111 requested changes

2022-03-02 18:08 UTC, 111Mihail111 commented on pages/manualDataEntry.html
> +                                    <div class="col-10">
Выровняй все колы в модалках по 12, где текстовые поля

2022-03-02 19:19 UTC, 111Mihail111 approved these changes

2022-03-02 19:45 UTC, merged