Задача 10 Изменил подход к позиционировании элементов на картинке кар…
111Mihail111/EVENTIME pull request #9
Opened 2022-03-03 16:09 UTC by kitovras

…точки

2022-03-03 16:12 UTC, JEN1011 approved these changes

2022-03-03 18:38 UTC, JEN1011 requested changes

2022-03-03 18:38 UTC, JEN1011 commented on pages/index.html
> +                            <div class="card" style="border: 0px">
На каждом диве с классом "card" должен быть атрибут onclick="cardDetailsVisible(true)", иначе мы не увидим доп. инфу по карте, исправь

2022-03-03 21:55 UTC, DjWaRCovAiK approved these changes

2022-03-04 18:08 UTC, JEN1011 approved these changes

2022-03-05 05:37 UTC, Roman-Popov-2021 approved these changes

2022-03-05 05:48 UTC, 111Mihail111 approved these changes

2022-03-05 08:10 UTC, merged